import { makeStyles } from '@material-ui/core';
const useStyles = makeStyles(theme=>({
    root:{
        display:'flex',
        minHeight:'100vh',
        backgroundSize:200,
        backgroundRepeat:'space',
        backgroundColor:`${theme.palette.primary.dark}`,
        backgroundImage:`url(/images/watermark-dark.svg)`,
        '& a':{textDecoration:'none', color:'inherit'},
    },
    container:{
        color:'#FFF',
        display:'flex',
        borderRadius:20,
        padding:'0 50px',
        margin:'20px auto',
        flexDirection:'column',
        justifyContent:'flex-start',
        backgroundColor:theme.palette.primary.main,
        '& > img':{ maxWidth:200, margin:'30px auto 0', },
        [theme.breakpoints.down('xs')]:{
            margin:0,
            borderRadius:0,
            padding:'20px 50px',
            '& > img':{ margin:'0 auto', },
        },
    },
    header:{
        display:'flex',
        flexWrap:'wrap',
        alignItems:'center',
        margin:'30px 0 auto',
        '& .MuiTypography-h5':{ fontSize:'1.5rem',flexGrow:1, },
        '& > span':{ textDecoration:'underline', fontWeight:100, cursor:'pointer',},
        '& .MuiTypography-subtitle2':{ minWidth:'100%',marginTop:10, fontSize:'1rem', fontWeight:'300', },
    },
    body:{
        display:'flex',
        margin:'auto',
        flexWrap:'wrap',
        alignItems:'center',
        justifyContent:'space-between',
        '& > .MuiFormControl-root':{
            width:'100%',
            maxWidth:'48%',
            fontWeight:100,
            marginBottom:10,
            '& > .MuiIconButton-root':{ color:'white',fontWeight:300 },
            '&.MuiFormControl-fullWidth, &:only-child':{ maxWidth:'unset', },
            '& .MuiFormHelperText-root:not(.Mui-error), & .MuiInputBase-root':{
                color:'white',
                fontWeight:100,
                '&:not(.Mui-error) fieldset':{ borderColor:'white' },
            },
        },
        [theme.breakpoints.down('xs')]:{
            '&':{ margin:'20px auto', },
            '& > .MuiFormControl-root':{ maxWidth:'unset', margin:'0 auto 10px auto', },
        },
    },
    actions:{
        display:'flex',
        flexWrap:'wrap',
        marginTop:'auto',
        textAlign:'center',
        flexDirection:'row',
        '& .MuiSvgIcon-root':{ fontSize:15, },
        '& .MuiButton-containedPrimary':{ backgroundColor:'#1c4f75' },
        '& .MuiButton-root':{ color:'#fff', margin:'0 10px 0 auto', },
        '& > .active-step-3':{width:'100%',textAlign:'center',marginBottom:10,'& .MuiSvgIcon-root:nth-child(1)':{color:theme.palette.secondary.main} },
        '& > .active-step-4':{width:'100%',textAlign:'center',marginBottom:10,'& .MuiSvgIcon-root:nth-child(2)':{color:theme.palette.secondary.main} },
        '& > .active-step-5':{width:'100%',textAlign:'center',marginBottom:10,'& .MuiSvgIcon-root:nth-child(3)':{color:theme.palette.secondary.main} },
    },
    Toolbar:{
        width:'100%',
        fontWeight:'300',
        justifyContent:'center',
    },
    welcome:{
        margin:'auto',
        color:'#FFF',
        borderRadius:20,
        padding:'20px',
        display:'flex',
        flexDirection:'column',
        alignContent:'center',
        justifyContent:'center',
        textAlign:'center',
        backgroundColor:theme.palette.primary.main,
        '& > img':{ maxWidth:200, margin:'0 auto', marginTop:30, },
        '& > .MuiTypography-h5':{ margin:'20px auto', },
        '& > .MuiButton-root':{ margin:'40px auto',color:'#fff' },
        '& > .MuiTypography-subtitle2':{ },
    },
}));

export default useStyles;